# Generated by Django 4.0.2 on 2022-03-01 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.CharField(max_length=30)),
            ],
        ),
    ]
