# Generated by Django 4.0.2 on 2022-03-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='states',
            field=models.CharField(choices=[('completion', '完了'), ('incompletion', '未完了')], default='incompletion', max_length=30),
        ),
    ]
