# Generated by Django 4.0.2 on 2022-03-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_to_do_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='states',
            field=models.CharField(choices=[('完了', 'completion'), ('未完了', 'incompletion')], default='incompletion', max_length=30),
        ),
    ]
