# Generated by Django 4.0.2 on 2022-03-29 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_alter_to_do_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='states',
            field=models.CharField(choices=[('completion', '完了'), ('incompletion', '未完了')], default='incompletion', max_length=30),
        ),
    ]
