# Generated by Django 4.0.2 on 2022-09-15 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_alter_to_do_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='期日'),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='task',
            field=models.CharField(max_length=10, verbose_name='タスク名'),
        ),
    ]
