# Generated by Django 4.0.2 on 2022-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_alter_to_do_deadline_alter_to_do_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do',
            options={'verbose_name_plural': 'Task'},
        ),
        migrations.AlterField(
            model_name='to_do',
            name='states',
            field=models.CharField(choices=[('1', '完了'), ('2', '未完了')], default='2', max_length=1),
        ),
    ]
